#!/bin/bash
# -*- coding: UTF8 -*-

name="$(basename $(pwd))"
phpPort="3333"

case "$1" in
    "php")
        php -S "${name,,}.test:${phpPort}"
    ;;
    "bs")
        browser-sync start -p "${name,,}.test:${phpPort}" --listen "${name,,}.test" -c browser-sync.config.js
    ;;
    *)
        echo "Type of server required, abort"
        exit 1
    
esac